# Generated by Django 5.1.15 on 2026-09-20 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dispatchapp", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(verbose_name="Delivery Date & Time"),
                ),
                (
                    "received_by",
                    models.CharField(
                        max_length=200, verbose_name="Customer / Received By"
                    ),
                ),
                (
                    "signature_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the person who signed / acknowledged receipt.",
                        max_length=200,
                        verbose_name="Acknowledgement / Signature",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, verbose_name="Delivery Remarks"),
                ),
                (
                    "pod_file",
                    models.FileField(
                        blank=True,
                        help_text="Photo or scanned document, if required.",
                        null=True,
                        upload_to="pod/",
                        verbose_name="Proof of Delivery (POD)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispatch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="dispatchapp.dispatch",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-delivered_at"],
            },
        ),
    ]
