# Generated by Django 5.1.15 on 2026-09-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="Your Company S.A. de C.V.", max_length=200
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, default="Distribution & Supply", max_length=200
                    ),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("phone", models.CharField(blank=True, default="", max_length=60)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=60,
                        verbose_name="Company Tax ID (RFC)",
                    ),
                ),
                ("currency_symbol", models.CharField(default="$", max_length=5)),
                ("currency_code", models.CharField(default="MXN", max_length=5)),
            ],
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
