# Generated by Django 5.1.15 on 2026-09-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="quote_terms",
            field=models.TextField(
                blank=True,
                default="Prices are quoted in MXN and are valid for the period shown above. Delivery times are estimated and confirmed on order acceptance.",
                verbose_name="Quotation terms & notes",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="quote_validity_days",
            field=models.PositiveIntegerField(
                default=15,
                help_text="How many days a quotation stays valid.",
                verbose_name="Quotation validity (days)",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="tax_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Untick to hide the tax line entirely.",
                verbose_name="Show tax on quotations",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="tax_label",
            field=models.CharField(
                default="IVA",
                help_text="Name shown for the tax, e.g. IVA, VAT, GST.",
                max_length=20,
                verbose_name="Tax label",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="tax_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=16,
                help_text="e.g. 16 for standard IVA, 8 for the border zone, 0 for exempt.",
                max_digits=5,
                verbose_name="Tax rate (%)",
            ),
        ),
    ]
