# Generated by Django 5.1.15 on 2026-09-24 06:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sitesetting_quote_terms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesetting",
            name="company_name",
            field=models.CharField(default="United Distributors Ltd", max_length=200),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="currency_code",
            field=models.CharField(default="BZD", max_length=5),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="tax_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=60,
                verbose_name="Company Tax ID (TIN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="tax_label",
            field=models.CharField(
                default="GST",
                help_text="Name shown for the tax, e.g. GST, VAT, IVA.",
                max_length=20,
                verbose_name="Tax label",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="tax_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("12.5"),
                help_text="e.g. 12.5 for Belize GST, 0 for exempt.",
                max_digits=5,
                verbose_name="Tax rate (%)",
            ),
        ),
    ]
