# Generated by Django 5.1.15 on 2026-09-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_sitesetting_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="incentive_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                help_text="Default incentive paid to a salesperson as a % of the gross margin they generate.",
                max_digits=5,
                verbose_name="Sales incentive (% of margin)",
            ),
        ),
    ]
