# Generated by Django 4.2.19 on 2026-10-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesetting_accounts_follow_invoice_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='accounts_follow_invoice_visibility',
            field=models.BooleanField(default=False, help_text='When enabled, Accounts and invoice-based financial reports use only invoices whose Show in UI checkbox is enabled. When disabled, accounting uses the complete ledger as normal.', verbose_name='Accounts follow invoice Show in UI'),
        ),
    ]
