# Generated by Django 5.1.15 on 2026-09-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="incentive_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Overrides the company default incentive % for this salesperson (blank = use default).",
                max_digits=5,
                null=True,
            ),
        ),
    ]
