# Generated by Django 5.1.15 on 2026-09-20 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "sku",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="Product Code / SKU"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pcs", "Piece(s)"),
                            ("box", "Box"),
                            ("case", "Case"),
                            ("kg", "Kilogram"),
                            ("g", "Gram"),
                            ("l", "Litre"),
                            ("ml", "Millilitre"),
                            ("pack", "Pack"),
                            ("dozen", "Dozen"),
                            ("bottle", "Bottle"),
                        ],
                        default="pcs",
                        max_length=10,
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "stock_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Optional. Leave as 0 if stock is not tracked.",
                        max_digits=12,
                        verbose_name="Available Quantity / Stock",
                    ),
                ),
                ("track_stock", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalogue.category",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["sku"], name="catalogue_p_sku_cbd1c1_idx"),
                    models.Index(fields=["name"], name="catalogue_p_name_7c6733_idx"),
                ],
            },
        ),
    ]
