# Generated by Django 5.1.15 on 2026-09-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_stockmovement"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="damaged_qty",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cumulative units returned damaged and written off (not sellable).",
                max_digits=12,
                verbose_name="Damaged / written-off stock",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="kind",
            field=models.CharField(
                choices=[
                    ("order_out", "Order placed (out)"),
                    ("return_in", "Return to stock (in)"),
                    ("damaged", "Damaged / write-off"),
                    ("restock", "Restock (in)"),
                    ("adjust", "Manual adjustment"),
                ],
                max_length=20,
            ),
        ),
    ]
