# Generated by Django 5.1.15 on 2026-09-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_product_damaged_qty_alter_stockmovement_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Purchase cost per unit — used for inventory valuation.",
                max_digits=12,
                verbose_name="Cost Price",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="reorder_point",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Flag for reorder when stock reaches this level (0 = no alert).",
                max_digits=12,
                verbose_name="Reorder point",
            ),
        ),
    ]
