# Generated by Django 5.1.15 on 2026-09-24 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_product_cost_price_product_reorder_point"),
        ("orders", "0002_order_completed_at_order_stock_committed"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="orders.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_prices",
                        to="catalogue.product",
                    ),
                ),
            ],
            options={
                "ordering": ["customer", "product"],
                "unique_together": {("customer", "product")},
            },
        ),
        migrations.CreateModel(
            name="PriceBreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_qty", models.DecimalField(decimal_places=2, max_digits=12)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_breaks",
                        to="catalogue.product",
                    ),
                ),
            ],
            options={
                "ordering": ["product", "min_qty"],
                "unique_together": {("product", "min_qty")},
            },
        ),
    ]
