# Generated by Django 5.1.15 on 2026-09-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0006_product_brand_product_long_description_productspec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Product photo — PNG, JPG or animated GIF.",
                null=True,
                upload_to="products/",
            ),
        ),
    ]
