# Generated by Django 5.1.15 on 2026-09-28 11:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0007_alter_product_image"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="expiry_alert_days",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Send an expiry alert this many days before a batch expires.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_perishable",
            field=models.BooleanField(
                default=False,
                help_text="Perishable item (e.g. vegetables). Stock is tracked in dated batches and sold earliest-expiry-first (FEFO).",
            ),
        ),
        migrations.CreateModel(
            name="StockBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "received_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "qty_received",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "qty_remaining",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "alerted_at",
                    models.DateField(
                        blank=True,
                        help_text="Last date an expiry alert was emailed for this batch.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="catalogue.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_batches",
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Stock batches",
                "ordering": ["expiry_date", "received_date", "id"],
            },
        ),
    ]
