# Generated by Django 5.1.15 on 2026-09-20 03:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dispatch_no",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("dispatched", "Dispatched"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "vehicle_details",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Vehicle Details"
                    ),
                ),
                ("driver_name", models.CharField(blank=True, max_length=150)),
                (
                    "driver_contact",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Driver Contact Number"
                    ),
                ),
                ("dispatch_date", models.DateField(default=django.utils.timezone.now)),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "special_instructions",
                    models.TextField(
                        blank=True, verbose_name="Special Delivery Instructions"
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatches_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "orders",
                    models.ManyToManyField(
                        related_name="dispatches", to="orders.order"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dispatches",
                "ordering": ["-created_at"],
            },
        ),
    ]
