# Generated by Django 5.1.15 on 2026-09-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_completed_at_order_stock_committed"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
