# Generated by Django 4.2.19 on 2026-09-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='show_in_ui',
            field=models.BooleanField(db_index=True, default=False, help_text='If enabled, this invoice will be visible in the user-facing invoice UI.'),
        ),
    ]
